[package]
name = "chatapp"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
askama = "0.14.0"
axum="0.8.4"
http = "1.3.1"
reqwest = { version = "0.12.22", features = ["json"] }
serde_json="1.0"
tokio = { version = "1.47.1", features = ["full"] }


